version: "3"

services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - internal_network
        environment:
              MYSQL_ROOT_PASSWORD: KairosKUP1234
              MYSQL_DATABASE: kairoskup
              MYSQL_USER: KairosKUP
              MYSQL_PASSWORD: KairosKUP1234

    swearingapi:
        build:
            context: ./swearingAPI
            dockerfile: Dockerfile
        image: alexibro/swearingapi
        networks: 
            - internal_network
        ports: 
            - "8080:8080" 

    kairoskup:
        build:
            context: ./kairoskup
            dockerfile: Dockerfile
        image: alexibro/kairoskup
        restart: on-failure
        ports: 
            - "8443:8443"
        networks:
            - internal_network
        depends_on:
            - db
            - swearingapi
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db/kairoskup?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            SPRING_DATASOURCE_USERNAME: KairosKUP
            SPRING_DATASOURCE_PASSWORD: KairosKUP1234
            DOCKER_INTERNAL_HOST: http://host.docker.internal
            SWEARING_API_PORT: 8080

networks:
    internal_network:
