web:
    build: .
    ports: 
        - "8080:8080"
    links:
        - db
    environment:
        - SPRING_DATASOURCE=jdbc:mysql://db/kairoskup
db:
    environment:
        - MYSQL_ROOT_PASSWORD=pass
        - MYSQL_DATABASE=kairoskup
    image: mysql:5.6